// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package hl7

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ProcessorConfigInputType  = "inputType"
	ProcessorConfigOutputType = "outputType"
)

func (ProcessorConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ProcessorConfigInputType: {
			Default:     "",
			Description: "",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
				config.ValidationInclusion{List: []string{"fhir", "hl7", "hl7v3"}},
			},
		},
		ProcessorConfigOutputType: {
			Default:     "",
			Description: "",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
				config.ValidationInclusion{List: []string{"fhir", "hl7", "hl7v3"}},
			},
		},
	}
}
